### ISSUE TITLE
servers.json never created?

### ISSUE THREAD

**Issue by Techbot121** [RogueException/DiscordBot#1]
the servers.json which is used to load the Settings for the (global) Modules is never created so:

``` c#
if (File.Exists($"{_dir}/servers.json"))
```

in https://github.com/RogueException/DiscordBot/blob/master/src/DiscordBot/Services/SettingsService.cs#L48

is never true and once the bot restarts it never loads the list again. 

Manually adding the servers.json solves this issue.

**Comment by RogueException** [comment]
I have a push coming out with the next Discord.Net alpha that removes the servers.json entirely
